FROM yingding/spark_base

ENV MASTER_CONTAINER_NAME=spark-master
ENV MASTER_CONTAINER_PORT=7077
ENV CORES=3
ENV MEMORY=6G
ENV SPARK_WORKER_WEBUI_PORT=8081
ENV SPARK_WORKER_LOG=/spark/logs
ENV EXTRA_JAR=/extraJar
ENV EXTRA_JAR_NAME=spark-mongo-driver-1.0-with-dependencies
# additional jar package from mvn central

# copy entry point to root
COPY ./scripts/worker/entrypoint.sh /
# set entry point runable
RUN chmod +x /entrypoint.sh

# copy default conf file to install additional package
COPY ./resources/log4j.properties ./resources/spark-env.sh ./resources/cluster/spark-defaults.conf $SPARK_HOME/conf/
RUN chmod +x $SPARK_HOME/conf/spark-env.sh

# ADD additional Runtime dependency for spark worker nodes
RUN mkdir $EXTRA_JAR
COPY ./resources/pom.xml $EXTRA_JAR
WORKDIR $EXTRA_JAR

# -B batch mode, no interactive
# https://stackoverflow.com/questions/42208442/maven-docker-cache-dependencies/52808343#52808343
RUN mvn -B --fail-never dependency:resolve && \
    mvn -B --fail-never package && \
    mv ${EXTRA_JAR}/target/${EXTRA_JAR_NAME}.jar ${SPARK_HOME}/jars && \
    rm -rf ./target && \
    mvn dependency:purge-local-repository -DactTransitively=false -DreResolve=false && \
    rm -rf /root/.m2/
# purge the local repository https://stackoverflow.com/questions/53841126/what-does-mvn-verify-command-do
# and also remove the maven /root/.m2 repository folder

# go back to root
WORKDIR /

EXPOSE 8081

# TODO: Change to entrypoint

# https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact
# run in shell form, the process will be run as a subprocess of sh, will not receive stop signal from docker stop
# https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example
# ENTRYPOINT $SPARK_HOME/bin/spark-class org.apache.spark.deploy.worker.Worker -c $CORES -m $MEMORY spark://$MASTER_CONTAINER_NAME:7077

# use -vv so that the terminate of subprocess by tini is visible in docker log,
# not using -vvv since it will generate output every seconds.
# https://hynek.me/articles/docker-signals/
ENTRYPOINT ["/tini", "-vv", "--", "/entrypoint.sh"]
