FROM yingding/spark_base

ENV SPARK_MASTER_PORT 7077
ENV SPARK_MASTER_WEBUI_PORT 8080
ENV SPARK_MASTER_LOG /spark/logs

# copy entry point to root
COPY ./scripts/master/entrypoint.sh /
# set entry point runable
RUN chmod +x /entrypoint.sh

# expose 4040 for the scala interactive shell to publish the job scheduler url
EXPOSE 8080 4040

# https://hynek.me/articles/docker-signals/
# use -vv so that the terminate of subprocess by tini is visible in docker log, not using -vvv since it will generate output every seconds.
ENTRYPOINT ["/tini", "-vv", "--", "/entrypoint.sh"]
# ENTRYPOINT $SPARK_HOME/bin/spark-class org.apache.spark.deploy.master.Master
