FROM yingding/spark_base

ENV MASTER_CONTAINER_NAME=spark-master
ENV CORES=3
ENV MEMORY=6G
ENV SPARK_WORKER_WEBUI_PORT 8081
ENV SPARK_WORKER_LOG /spark/logs

# copy entry point to root
COPY ./scripts/worker/entrypoint.sh /
# set entry point runable
RUN chmod +x /entrypoint.sh

EXPOSE 8081

# TODO: Change to entrypoint

# https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact
# run in shell form, the process will be run as a subprocess of sh, will not receive stop signal from docker stop
# https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example
# ENTRYPOINT $SPARK_HOME/bin/spark-class org.apache.spark.deploy.worker.Worker -c $CORES -m $MEMORY spark://$MASTER_CONTAINER_NAME:7077

# use -vv so that the terminate of subprocess by tini is visible in docker log,
# not using -vvv since it will generate output every seconds.
# https://hynek.me/articles/docker-signals/
ENTRYPOINT ["/tini", "-vv", "--", "/entrypoint.sh"]
