FROM yingding/spark_base

ENV SPARK_MASTER_PORT 7077
ENV SPARK_MASTER_WEBUI_PORT 8080
ENV SPARK_MASTER_LOG /spark/logs

# expose 4040 for the scala interactive shell to publish the job scheduler url
EXPOSE 8080 4040

ENTRYPOINT $SPARK_HOME/bin/spark-class org.apache.spark.deploy.master.Master
